modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Mrbysco/TimeStages"
license="MIT"

[[mods]]
modId="timestages"
version="${file.jarVersion}"
displayName="Time Stages"
displayURL="https://www.curseforge.com/minecraft/mc-mods/time-stages"
authors="Mrbysco, ShyNieke"
description='''
Allows stages to be unlocked/locked with timers
'''

[[dependencies.timestages]]
modId="gamestages"
mandatory=true
versionRange="[11.0.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.timestages]]
modId="crafttweaker"
mandatory=true
versionRange="[10.0.2,)"
ordering="NONE"
side="BOTH"